### ISSUE TITLE
Package names are not normalized

### ISSUE THREAD

**Issue by encukou** [fedora-python/pyp2rpm#144]
`pip` normalizes package names as per [PEP 503](https://www.python.org/dev/peps/pep-0503/#normalized-names), so `pip install flask` and `pip install Flask` will both work.
However, pyp2rpm doesn't seem to do this:

```console
$ pyp2rpm flask
Package "flask" could not be found on PyPI.
```

**Comment by irushchyshyn** [comment]
Seems like this is a known issue with PyPI XMLRPC API (that we are using), see https://github.com/pypa/pypi-legacy/issues/418.

As suggested in the issue, we can point the client to the warehouse installation, where the issue is already fixed. The change needed is [here](https://github.com/irushchyshyn/pyp2rpm/commit/6b7bfec72f9587efe4c644173a5d1e68ff88f10f) and normalization will work. However, as it is a pre-production deployment of Warehouse, I am not sure if it is time to change it.
