### ISSUE TITLE
How create package sentry only python2?

### ISSUE THREAD

**Issue by patsevanton** [fedora-python/pyp2rpm#219]
Sentry has a Python 2 only wheel and no sdist
https://github.com/fedora-python/pyp2rpm/issues/218

cat /etc/redhat-release 
Fedora release 31 (Thirty One)
pip install --user pyp2rpm
pyp2rpm sentry -t epel7 -b 2 -v 9.1.2:
```
...
%package -n     python2-%{pypi_name}
...
%package -n     python%{python3_pkgversion}-%{pypi_name}
...
```

How create package sentry only python2?
Thanks!

**Comment by gordonmessmer** [comment]
pyp2rpm has a wheel metadata parser for an old version of the wheel metadata.  However, the wheel metadata format has changed, and no longer includes a lot of the information that pyp2rpm expects.  It isn't possible to create a spec for recently-built wheels.

Since Fedora, at least, requires the source for any software to be included in the distribution, support for packaging wheels will be removed in a future release.

**Comment by hroncok** [comment]
Try using the GH tarball: `pyp2rpm https://github.com/getsentry/sentry/releases/download/9.1.2/sentry-9.1.2.tar.gz -t epel7 -b 2`

**Comment by patsevanton** [comment]
```
pyp2rpm https://github.com/getsentry/sentry/releases/download/9.1.2/sentry-9.1.2.tar.gz -t epel7 -b 2
Package "https://github.com/getsentry/sentry/releases/download/9.1.2/sentry-9.1.2.tar.gz" could not be found on PyPI.
```

**Comment by patsevanton** [comment]
On Centos 7
```
sudo yum install -y epel-release rpmdevtools mc
sudo yum install -y python34 python3-pip 
pip3 install --user pyp2rpm
pyp2rpm sentry -t epel7 -b2 -p2 -v 9.1.2 -s sentry-9.1.2.spec
SPEC file is printed in the console
We write the SPEC file from the console to sentry-9.1.2.spec
vi sentry-9.1.2.spec
spectool -g -R sentry-9.1.2.spec
sudo yum install -y python2-devel
sudo yum-builddep sentry-9.1.2.spec
rpmbuild -bb sentry-9.1.2.spec

```
